### ISSUE TITLE
[Filters.jsx]: Separate event callbacks into independent functions.

### ISSUE THREAD

**Issue by gerardramonp** [SkylabCoders/pet-finder#35]
Filters.jsx has 3 synthetic events (onClick, onChange...).

Separate that callback into an individual function so that the code is more simple and easy to read.

Also, the onChange event has the same code block, the only diference is the property which is using (gender / age), you could pass that property name as a function parameter and use the same function for the 2 events.

Tip: remember the bracket notation when acessing properties: **myObject['propertyName']**

**Comment by Jheavi** [comment]
Done
