### ISSUE TITLE
Remove console.log's in various files (index, actions, MainDetail, FIlters)

### ISSUE THREAD

**Issue by gerardramonp** [SkylabCoders/pet-finder#36]
You can use the VS code **"Search"** function:

![image](https://user-images.githubusercontent.com/27928797/97985683-e100ce80-1dd8-11eb-975f-65f2e929d7fe.png)

**Comment by Jheavi** [comment]
We have removed some of the console.logs, but we want to maintain three to see if the app makes infinite fetchs like a problem we had a day ago

**Comment by Jheavi** [comment]
Done!
